name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: "0 16 * * *" # Runs every day at 16:00 UTC (0:00 at CST)
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://blog.kisechan.space/atom.xml"
          max_post_count: 5
          date_format: "yyyy-mm-dd"
          custom_tags: "post_tags/category:term/"
          template: >-
            <li> $randomEmoji(ğŸˆ,ğŸ‡,ğŸ,ğŸ€,ğŸ’) <a href="$url">$title</a> | ğŸ—“ <b>$date</b> </li>$newline
          comment_tag_name: "BLOG-POST-LIST"
          readme_path: "README.md"
          commit_message: "Automatically updated blog post list"
          # committer_email: "kisechan_@outlook.com"
          committer_username: "Blog-Post-Bot"
          # categories_template: "<code>$category</code>"
